### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by larspb2** [samuelba/content_select_downloader#1]
Hi, thank you very much for this script. Sadly I can't get it to work. This is the error I get every time.

[name@name content_select_downloader-master]$ python3 ./download.py --url https://content-2select-1com-REMOVED.de/media/moz_viewer/BOOKID/language:de --output  allgemein.pdf
Download from url: https://content-2select-1com-REMOVED.de/media/moz_viewer/BOOKID/language:de
Resulting PDF name: allgemein.pdf
Get PDF id.
PDF id: BOOKID
Get chapter ids.
Traceback (most recent call last):
  File "/home/name/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/name/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/name/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/name/.local/lib/python3.8/site-packages/urllib3/connection.py", line 386, in connect
    self.sock = ssl_wrap_socket(
  File "/home/name/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/name/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/name/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/home/name/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='content-2select-1com-REMOVED.de', port=443): Max retries exceeded with url: /media/moz_viewer/BOOKID/language:de (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./download.py", line 135, in <module>
    downloader.run()
  File "./download.py", line 127, in run
    chapter_ids = self.get_chapter_ids(self.url)
  File "./download.py", line 61, in get_chapter_ids
    resp = session.get(url)
  File "/home/name/.local/lib/python3.8/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/name/.local/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/name/.local/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/name/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='content-2select-1com-REMOVED.de', port=443): Max retries exceeded with url: /media/moz_viewer/BOOKID/language:de (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))
    
I changed:

resp = session.get(url)
to 
resp = session.get(url, verify=False)

resulting in pyppeteer.errors.PageError: net::ERR_CERT_AUTHORITY_INVALID at REMOVED/login.html

**Comment by jonasmeier1212** [comment]
I had the same issue and the problem was IPv6. Do you use Mac?

**Comment by samuelba** [comment]
I don't think it works anymore as they changed something, would have to be updated.

**Comment by Spiderschwein** [comment]
I got it to work. So in general it's usable today.

I had to use python36 as requests-html only supports python36 (https://docs.python-requests.org/projects/requests-html/en/latest/) and had to do some adjustments in the pypdf2 lib. (https://stackoverflow.com/a/52687771/535469)

So, i dont think it's directly related to your exception but i just wanted to let you know it's usable until today.

**Comment by Klexx** [comment]
@samuelba it still works fine :)
